const { test, expect } = require('@playwright/test');
const { resetApp } = require('./helpers');

async function waitForDecision(page){await page.waitForFunction(()=>globalThis.LifeOS?.app?.decisionEngine&&globalThis.LifeOS?.ProjectAllocator,null,{timeout:20_000})}
async function seedTask(page,overrides={}){return page.evaluate(async overrides=>LifeOS.app.repo.save('tasks',{id:`d461-${crypto.randomUUID()}`,title:'Decision 4.6.1 task',status:'Next',priority:'Medium',estimatedDuration:60,minimumSessionDuration:15,maximumSessionDuration:120,actualMinutes:0,plannedMinutes:0,blockedBy:[],schedulingFlexibility:'flexible',workMode:'Normal',context:'General',postponeCount:0,...overrides},{validate:false}),overrides)}
async function seedProject(page,overrides={}){return page.evaluate(async overrides=>LifeOS.app.repo.save('projects',{id:`p461-${crypto.randomUUID()}`,title:'Decision project',status:'Active',priority:'High',planningMode:'Weekly Flexible',minimumWeeklyHours:2,weeklyTargetHours:6,stretchWeeklyHours:8,minimumSessionMinutes:15,maximumSessionMinutes:120,workDayMaxHours:4,offDayMaxHours:6,universityDayMaxHours:4,mixedDayMaxHours:4,recoveryDayMaxHours:2,customDayMaxHours:4,...overrides},{validate:false}),overrides)}
async function planningHash(page){return page.evaluate(async()=>{const data=await LifeOS.app.repo.dataset({fresh:true}),settings=await LifeOS.app.repo.settings();return LifeOS.CoreUtil.hash({tasks:data.tasks||[],projects:data.projects||[],events:data.events||[],timeBlocks:data.timeBlocks||[],dayProfiles:data.dayProfiles||[],settings})})}
async function manualCandidate(page,taskId,{date=null,startMinute=720,duration=30,mode='production'}={}){return page.evaluate(async args=>{const date=args.date||LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),request={id:`manual-${crypto.randomUUID()}`,type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:args.mode,source:'461-certification'},context=await new LifeOS.DecisionContextBuilder().build(request),task=context.tasks.find(t=>t.id===args.taskId),candidate={id:`manual-${args.taskId}-${args.startMinute}`,kind:'task-session',taskId:task.id,projectId:task.projectId||'',title:task.title,duration:args.duration,date,startMinute:args.startMinute,changes:[],metadata:{},affectedEntityIds:[task.id]},feasibility=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),tradeoffs=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,feasibility),row={candidate,feasibility,tradeoffs,rank:1,label:'Recommended'};row.explanation=new LifeOS.DecisionExplanationEngine().explain(row,null,context);return{decisionId:`manual-decision-${crypto.randomUUID()}`,request,contextFingerprint:context.contextFingerprint,dataGeneration:context.dataGeneration,engineVersion:LifeOS.decisionEngineVersion,generatedAt:new Date().toISOString(),dataQuality:context.dataQuality,alternatives:[row],recommended:row}}, {taskId,...arguments[1]})}

test.describe('LifeOS 4.6.1 Decision Planning Completion',()=>{
  test.beforeEach(async({page})=>{await resetApp(page);await waitForDecision(page)});

  test('exports 4.6.1 identity and authoritative ProjectAllocator',async({page})=>{const x=await page.evaluate(()=>({app:LifeOS.version,decision:LifeOS.decisionEngineVersion,allocator:typeof LifeOS.ProjectAllocator,rule:LifeOS.ruleEngineVersion,db:LifeOS.schemaVersion}));expect(x).toEqual({app:'4.6.1',decision:'4.6.1',allocator:'function',rule:'4.5.1',db:16})});

  test('TODAY_PLAN creates a genuine multi-task whole-day plan',async({page})=>{await seedTask(page,{title:'Day A',priority:'High',estimatedDuration:45});await seedTask(page,{title:'Day B',priority:'High',estimatedDuration:45,context:'Study'});const result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),p=d.alternatives.find(x=>x.candidate.kind==='day-plan');return{count:p?.candidate.plan.planned.length||0,ids:p?.candidate.plan.planned.map(x=>x.block.taskId)||[],minutes:p?.candidate.duration||0}});expect(result.count).toBeGreaterThanOrEqual(2);expect(new Set(result.ids).size).toBeGreaterThanOrEqual(2);expect(result.minutes).toBeGreaterThan(0)});

  test('DEADLINE_TRIAGE builds a real deadline-only multi-task plan',async({page})=>{const date=await page.evaluate(()=>LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1));const a=await seedTask(page,{title:'Urgent A',priority:'Critical',deadline:date,estimatedDuration:30}),b=await seedTask(page,{title:'Urgent B',priority:'High',deadline:date,estimatedDuration:30}),later=await seedTask(page,{title:'No deadline',priority:'High',estimatedDuration:30});const result=await page.evaluate(async({date,laterId})=>{const d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.DEADLINE_TRIAGE,date,mode:'production',constraints:{horizonDays:1}}),p=d.alternatives.find(x=>x.candidate.kind==='deadline-triage-plan');return{count:p?.candidate.plan.planned.length||0,ids:p?.candidate.plan.planned.map(x=>x.block.taskId)||[],cutoff:p?.candidate.metadata.deadlineCutoff}}, {date,laterId:later.id});expect(result.count).toBeGreaterThanOrEqual(2);expect(result.ids).not.toContain(later.id);expect(result.ids).toEqual(expect.arrayContaining([a.id,b.id]))});

  test('PROJECT_ALLOCATION uses real project shortfall and weekly allocation plans',async({page})=>{const p=await seedProject(page,{minimumWeeklyHours:4,weeklyTargetHours:8});await seedTask(page,{title:'Project A',projectId:p.id,priority:'High',estimatedDuration:180});await seedTask(page,{title:'Project B',projectId:p.id,priority:'High',estimatedDuration:180});const result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.PROJECT_ALLOCATION,date,mode:'production'}),plans=d.alternatives.filter(x=>x.candidate.kind==='project-allocation-plan');return plans.map(x=>({blocks:x.candidate.plan.planned.length,mode:x.candidate.metadata.allocationMode,projectEffect:x.tradeoffs.projectEffect}))});expect(result.length).toBeGreaterThan(0);expect(result.some(x=>x.blocks>0)).toBeTruthy();expect(result.some(x=>x.projectEffect&&Number.isFinite(x.projectEffect.shortfallBefore))).toBeTruthy()});

  test('DEFERRAL creates a concrete postponement mutation',async({page})=>{const task=await seedTask(page,{title:'Defer me',priority:'Low'}),before=await planningHash(page);const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.DEFERRAL,date,mode:'production',entityIds:[taskId]}),p=d.alternatives.find(x=>x.candidate.kind==='deferral-plan'&&x.candidate.taskId===taskId),change=p?.candidate.changes.find(c=>c.store==='tasks');return{target:p?.candidate.targetDate,preferred:change?.after.preferredDate,postpone:change?.after.postponeCount,kind:p?.candidate.kind}},task.id);expect(result.kind).toBe('deferral-plan');expect(result.target).toBe(result.preferred);expect(result.postpone).toBeGreaterThan(0);expect(await planningHash(page)).toBe(before)});

  test('WEEK_PRIORITY creates an actual seven-day priority plan',async({page})=>{await seedTask(page,{title:'Critical week',priority:'Critical',estimatedDuration:120});await seedTask(page,{title:'High week',priority:'High',estimatedDuration:120});const result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.WEEK_PRIORITY,date,mode:'production'}),p=d.alternatives.find(x=>x.candidate.kind==='week-priority-plan');return{blocks:p?.candidate.plan.planned.length||0,days:new Set((p?.candidate.plan.planned||[]).map(x=>x.block.date)).size,mode:p?.candidate.metadata.priorityMode}});expect(result.blocks).toBeGreaterThan(0);expect(result.mode).toBeTruthy()});

  test('SCHEDULE_CONFLICT surfaces real ScheduleRepairEngine candidates',async({page})=>{const task=await seedTask(page,{title:'Conflict task',status:'Scheduled',priority:'High',estimatedDuration:90,plannedMinutes:90,minimumSessionDuration:90,maximumSessionDuration:90});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1);await LifeOS.app.repo.save('timeBlocks',{id:`tb-${crypto.randomUUID()}`,taskId,title:'Conflict task',date,startTime:'15:30',endTime:'17:00',duration:90,type:'task',locked:false,protected:false,manuallyPlaced:false,sourceType:'scheduler',revision:1},{validate:false});await LifeOS.app.repo.save('events',{id:`ev-${crypto.randomUUID()}`,title:'Fixed event',kind:'Meeting',startDate:date,endDate:date,startTime:'14:00',endTime:'16:20',fixedOrFlexible:'Fixed',locked:true,travelBefore:0,travelAfter:0,preparationTime:0,revision:1},{validate:false});const d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.SCHEDULE_CONFLICT,date,mode:'production'}),p=d.alternatives.find(x=>x.candidate.kind==='schedule-conflict-plan');return{found:Boolean(p),changes:p?.candidate.changes.length||0,repairId:p?.candidate.repairCandidateId||''}},task.id);expect(result.found).toBeTruthy();expect(result.changes).toBeGreaterThan(0);expect(result.repairId).toBeTruthy()});

  test('RecoveryTimeEngine protected windows are hard feasibility',async({page})=>{const task=await seedTask(page,{title:'Recovery collision'});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1);await LifeOS.app.repo.setting('recoveryMode','protected');await LifeOS.app.repo.setting('recoveryAfterWorkMinutes',45);await LifeOS.app.repo.save('events',{id:`work-${crypto.randomUUID()}`,title:'Work shift',kind:'Work',startDate:date,endDate:date,startTime:'06:00',endTime:'14:00',travelAfter:60,travelBefore:0,preparationTime:0,fixedOrFlexible:'Fixed',revision:1},{validate:false});const request={type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'},context=await new LifeOS.DecisionContextBuilder().build(request),candidate={id:'recovery-hard',kind:'task-session',taskId,title:'Recovery collision',duration:30,date,startMinute:15*60+15,changes:[],affectedEntityIds:[taskId]};return new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context)},task.id);expect(result.feasible).toBeFalsy();expect(result.blockers.join(' ')).toContain('Protected recovery')});

  test('ContextSwitchEngine contributes real transition cost',async({page})=>{const prev=await seedTask(page,{title:'Finance previous',context:'Finance'}),task=await seedTask(page,{title:'Study next',context:'Study'});const result=await page.evaluate(async({prevId,taskId})=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1);await LifeOS.app.repo.save('timeBlocks',{id:`ctx-${crypto.randomUUID()}`,taskId:prevId,title:'Finance previous',date,startTime:'14:00',endTime:'15:00',duration:60,type:'task',locked:false,revision:1},{validate:false});const request={type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'},context=await new LifeOS.DecisionContextBuilder().build(request),candidate={id:'ctx-candidate',kind:'task-session',taskId,title:'Study next',duration:60,date,startMinute:15*60,changes:[],affectedEntityIds:[taskId]},f=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),t=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,f);return{cost:t.contextCost,reasons:t.reasons.map(r=>r.reasonCode)}},{prevId:prev.id,taskId:task.id});expect(result.cost).toBeGreaterThan(0);expect(result.reasons).toContain('CONTEXT-SWITCH')});

  test('ScheduleStabilityEngine quantifies decision disruption',async({page})=>{const task=await seedTask(page,{title:'Stability target'});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),request={type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'},context=await new LifeOS.DecisionContextBuilder().build(request),candidate={id:'stability',kind:'task-session',taskId,title:'Stability target',duration:30,date,startMinute:12*60,changes:[],affectedEntityIds:[taskId]},f=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),t=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,f);return t.stability},task.id);expect(result.addedBlockCount).toBeGreaterThan(0);expect(result.disruptionCost).toBeGreaterThan(0);expect(Number.isFinite(result.score)).toBeTruthy();expect(result.score).toBeGreaterThanOrEqual(0);expect(result.score).toBeLessThanOrEqual(100)});

  test('ProjectAllocator can hard-reject a candidate above project allowance',async({page})=>{const p=await seedProject(page,{workDayMaxHours:.25,offDayMaxHours:.25,universityDayMaxHours:.25,mixedDayMaxHours:.25,recoveryDayMaxHours:.25,customDayMaxHours:.25,minimumWeeklyHours:0,weeklyTargetHours:1,stretchWeeklyHours:1}),task=await seedTask(page,{title:'No project allowance',projectId:p.id});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),context=await new LifeOS.DecisionContextBuilder().build({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),candidate={id:'project-hard',kind:'task-session',taskId,title:'No project allowance',duration:30,date,startMinute:12*60,changes:[],affectedEntityIds:[taskId]};return new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context)},task.id);expect(result.feasible).toBeFalsy();expect(result.blockers.join(' ')).toContain('Project/capacity allowance')});

  test('matched automatic RuleEngine placement rule becomes a hard constraint',async({page})=>{const task=await seedTask(page,{title:'Overdue ruled task',deadline:await page.evaluate(()=>LifeOS.CoreUtil.localDate())});const result=await page.evaluate(async taskId=>{await LifeOS.app.repo.save('rules',{id:'d461-hard-rule',name:'Overdue at ten',description:'',enabled:true,trigger:{type:'task-overdue',config:{}},conditionMode:'all',conditions:[],actions:[{type:'set-preferred-time',params:{time:'10:00',toleranceMinutes:0}}],priority:90,scope:{},executionPolicy:'automatic',source:'manual',schemaVersion:1,ruleEngineVersion:'4.5.1',revision:1},{validate:false});await LifeOS.app.ruleEngine.reindex();const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),context=await new LifeOS.DecisionContextBuilder().build({type:LifeOS.DECISION_TYPES.NEXT_ACTION,date,mode:'production'}),candidate={id:'rule-hard-candidate',kind:'task-session',taskId,title:'Overdue ruled task',duration:30,date,startMinute:12*60,changes:[],affectedEntityIds:[taskId]};return new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context)},task.id);expect(result.feasible).toBeFalsy();expect(result.blockers.join(' ')).toContain('Rule Overdue at ten requires time')});

  test('before/after DeadlineEngine forecast effect is exposed',async({page})=>{const date=await page.evaluate(()=>LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1)),task=await seedTask(page,{title:'Forecast target',priority:'Critical',deadline:date,estimatedDuration:120});const result=await page.evaluate(async({taskId,date})=>{const context=await new LifeOS.DecisionContextBuilder().build({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),candidate={id:'forecast-effect',kind:'task-session',taskId,title:'Forecast target',duration:60,date,startMinute:9*60,changes:[],affectedEntityIds:[taskId]},f=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),t=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,f);return{effect:t.forecastEffect,reasons:t.reasons.map(r=>r.reasonCode)}},{taskId:task.id,date});expect(result.effect.shortfallAfter).toBeLessThanOrEqual(result.effect.shortfallBefore);expect(result.reasons).toContain('FORECAST-BEFORE-AFTER')});

  test('opportunity costs are quantified in minutes and explained',async({page})=>{const task=await seedTask(page,{title:'Opportunity target',priority:'High'});await seedTask(page,{title:'Competing demand',priority:'High',estimatedDuration:600});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),context=await new LifeOS.DecisionContextBuilder().build({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),candidate={id:'opp',kind:'task-session',taskId,title:'Opportunity target',duration:60,date,startMinute:9*60,changes:[],affectedEntityIds:[taskId]},f=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),t=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,f),row={candidate,feasibility:f,tradeoffs:t};return{minutes:t.opportunityCostMinutes,text:new LifeOS.DecisionExplanationEngine().explain(row,null,context).opportunityCost}},task.id);expect(Number.isFinite(result.minutes)).toBeTruthy();expect(result.minutes).toBeGreaterThanOrEqual(0);expect(result.text).toMatch(/\d+ minutes/)});

  test('hard feasibility fails closed when ConflictEngine validation throws',async({page})=>{const task=await seedTask(page,{title:'Fail closed target'});const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),context=await new LifeOS.DecisionContextBuilder().build({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),candidate={id:'fail-closed',kind:'task-session',taskId,title:'Fail closed target',duration:30,date,startMinute:12*60,changes:[],affectedEntityIds:[taskId]},original=LifeOS.ConflictEngine.checkInterval;LifeOS.ConflictEngine.checkInterval=()=>{throw new Error('forced validator outage')};try{return new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context)}finally{LifeOS.ConflictEngine.checkInterval=original}},task.id);expect(result.feasible).toBeFalsy();expect(result.blockers.join(' ')).toContain('failed closed')});

  test('scenario Apply is rejected before any production mutation',async({page})=>{const task=await seedTask(page,{title:'Scenario apply target',priority:'Critical'}),before=await planningHash(page);const result=await page.evaluate(async taskId=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),request={id:'scenario-manual',type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'scenario',source:'cert',scenarioId:''},context=await new LifeOS.DecisionContextBuilder().build(request),candidate={id:'scenario-candidate',kind:'task-session',taskId,title:'Scenario apply target',duration:30,date,startMinute:12*60,changes:[],affectedEntityIds:[taskId]},f=new LifeOS.DecisionFeasibilityGate().evaluate(candidate,context),t=new LifeOS.DecisionTradeoffEngine().evaluate(candidate,context,f),row={candidate,feasibility:f,tradeoffs:t,rank:1,label:'Recommended'};row.explanation=new LifeOS.DecisionExplanationEngine().explain(row,null,context);const decision={decisionId:'scenario-decision',request,contextFingerprint:context.contextFingerprint,dataGeneration:context.dataGeneration,engineVersion:LifeOS.decisionEngineVersion,generatedAt:new Date().toISOString(),dataQuality:context.dataQuality,alternatives:[row],recommended:row};try{await LifeOS.app.decisionEngine.apply(decision,candidate.id);return{applied:true,code:''}}catch(error){return{applied:false,code:error.code||''}}},task.id);expect(result.applied).toBeFalsy();expect(result.code).toBe('DECISION-SCENARIO-APPLY-461');expect(await planningHash(page)).toBe(before)});

  test('whole-day multi-task Apply is one Undo and restores the exact planning state',async({page})=>{await seedTask(page,{title:'Atomic day A',priority:'Critical',estimatedDuration:45});await seedTask(page,{title:'Atomic day B',priority:'High',estimatedDuration:45});const before=await planningHash(page),result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),p=d.alternatives.find(x=>x.candidate.kind==='day-plan');if(!p)throw new Error('Missing day-plan candidate');const applied=await LifeOS.app.decisionEngine.apply(d,p.candidate.id),data=await LifeOS.app.repo.dataset({fresh:true}),created=(data.timeBlocks||[]).filter(b=>b.decisionId===d.decisionId);return{created:created.length,operationId:applied.operationId}},);expect(result.created).toBeGreaterThanOrEqual(2);expect(result.operationId).toBeTruthy();await page.evaluate(async()=>LifeOS.app.undo.undo());expect(await planningHash(page)).toBe(before)});

  test('whole-day plan recommendation and block projection remain deterministic over 20 analyses',async({page})=>{await seedTask(page,{title:'Deterministic A',priority:'Critical',estimatedDuration:45});await seedTask(page,{title:'Deterministic B',priority:'High',estimatedDuration:45});const result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),rows=[];for(let i=0;i<20;i++){const d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'production'}),p=d.alternatives.find(x=>x.candidate.kind==='day-plan');rows.push({id:p?.candidate.id||'',projection:(p?.candidate.plan.planned||[]).map(x=>[x.block.id,x.block.taskId,x.block.date,x.block.startTime,x.block.duration])})}return rows});expect(new Set(result.map(x=>x.id)).size).toBe(1);expect(new Set(result.map(x=>JSON.stringify(x.projection))).size).toBe(1)});

  test('all nine Decision types execute through concrete analyzers without throwing',async({page})=>{await seedTask(page,{title:'Coverage task',priority:'High',estimatedDuration:30});const result=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),types=Object.values(LifeOS.DECISION_TYPES),out={};for(const type of types){try{const d=await LifeOS.app.decisionEngine.analyze({type,date,mode:'production'});out[type]={ok:true,alternatives:d.alternatives.length}}catch(error){out[type]={ok:false,message:error.message}}}return out});expect(Object.keys(result)).toHaveLength(9);expect(Object.values(result).every(x=>x.ok)).toBeTruthy()});

  test('preview for a multi-task plan remains immutable and exposes forecast/opportunity evidence',async({page})=>{await seedTask(page,{title:'Preview day A',priority:'High',estimatedDuration:30});await seedTask(page,{title:'Preview day B',priority:'High',estimatedDuration:30});const before=await planningHash(page),preview=await page.evaluate(async()=>{const date=LifeOS.CoreUtil.addDays(LifeOS.CoreUtil.localDate(),1),d=await LifeOS.app.decisionEngine.analyze({type:LifeOS.DECISION_TYPES.TODAY_PLAN,date,mode:'preview'}),p=d.alternatives.find(x=>x.candidate.kind==='day-plan');return LifeOS.app.decisionEngine.preview(d,p.candidate.id)});expect(preview.immutable).toBeTruthy();expect(preview.proposed.blockCount).toBeGreaterThanOrEqual(2);expect(preview.forecastEffect).toBeTruthy();expect(Number.isFinite(preview.opportunityCostMinutes)).toBeTruthy();expect(await planningHash(page)).toBe(before)});
});
