from pathlib import Path

p = Path('verify-420/LifeOS_4_2_Scenario_Forecasting_Standalone.html')
s = p.read_text()
start = s.index('  class ComputeManager{')
end = s.index('\n\n  class RecordDiff{', start)
new = r'''  class ComputeManager{
    constructor(){this.worker=null;this.workerInitPromise=null;this.jobs=new Map();this.mode='Main-thread fallback';this.jobTypes=new Set(['aggregate','monte-carlo']);this.protocol='LifeOSCompute';this.protocolVersion=1;this.init()}
    bind(worker,mode='Available'){this.worker=worker;worker.onmessage=event=>this.receive(event.data);worker.onerror=()=>{if(this.worker===worker){this.mode='Main-thread fallback';worker.terminate();this.worker=null}};this.mode=mode;return true}
    init(){if(typeof Worker!=='function'||location.protocol==='file:')return false;if(globalThis.navigator?.onLine===false&&globalThis.caches){this.workerInitPromise=this.initCached().finally(()=>{this.workerInitPromise=null});return false}try{return this.bind(new Worker('./planning-worker.js'))}catch{return false}}
    async initCached(){if(this.worker)return true;if(typeof Worker!=='function'||location.protocol==='file:'||!globalThis.caches||!globalThis.Blob||!globalThis.URL?.createObjectURL)return false;try{const workerUrl=new URL('./planning-worker.js',location.href).href,response=await caches.match(workerUrl);if(!response)return false;const source=await response.text();if(!source.includes('LifeOSCompute'))return false;const blobUrl=URL.createObjectURL(new Blob([source],{type:'text/javascript'})),worker=new Worker(blobUrl);this.bind(worker,'Available · cached offline');setTimeout(()=>URL.revokeObjectURL(blobUrl),1000);return true}catch{return false}}
    async ensureWorker(){if(this.worker)return true;if(this.workerInitPromise){await this.workerInitPromise.catch(()=>false);if(this.worker)return true}if(globalThis.navigator?.onLine===false&&globalThis.caches){this.workerInitPromise=this.initCached().finally(()=>{this.workerInitPromise=null});await this.workerInitPromise.catch(()=>false);return Boolean(this.worker)}return this.init()}
    async run(type,payload={},options={}){if(!this.jobTypes.has(type))throw CoreUtil.error('COMPUTE-JOB-001','Unsupported compute job.',{type});const jobId=CoreUtil.uid(),dataGeneration=Number(options.dataGeneration||0);await this.ensureWorker();if(!this.worker){const value=this.fallback(type,payload,dataGeneration);options.onProgress?.({progress:1,stage:'Complete'});return value}return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{this.cancel(jobId);reject(CoreUtil.error('COMPUTE-TIMEOUT-002','Background computation timed out.'))},options.timeoutMs||15000);this.jobs.set(jobId,{resolve,reject,timeout,dataGeneration,onProgress:typeof options.onProgress==='function'?options.onProgress:null});this.worker.postMessage({protocol:this.protocol,protocolVersion:this.protocolVersion,jobId,type,dataGeneration,payload})})}
    fallback(type,payload,dataGeneration){if(type==='aggregate'){const values=CoreUtil.array(payload.values).map(Number).filter(Number.isFinite);return{jobId:'main-thread',status:'complete',dataGeneration,result:{count:values.length,sum:values.reduce((a,b)=>a+b,0),average:values.length?values.reduce((a,b)=>a+b,0)/values.length:0},mode:'Main-thread fallback'}}if(type==='monte-carlo'){if(CoreUtil.num(payload.simulations,2000)>500)throw CoreUtil.error('COMPUTE-WORKER-REQUIRED-006','Detailed probabilistic simulation requires the local background worker.');return{jobId:'main-thread',status:'complete',dataGeneration,result:MonteCarloEngine.run({...payload,simulations:Math.min(500,CoreUtil.num(payload.simulations,500))}),mode:'Main-thread quick fallback'}}throw CoreUtil.error('COMPUTE-JOB-001','Unsupported compute job.')}
    receive(message){if(!message||message.protocol!==this.protocol||message.protocolVersion!==this.protocolVersion||typeof message.jobId!=='string')return false;const job=this.jobs.get(message.jobId);if(!job)return false;if(message.status==='progress'){job.onProgress?.({progress:Number(message.progress||0),stage:String(message.stage||'Calculating')});return true}if(message.status==='complete'){clearTimeout(job.timeout);this.jobs.delete(message.jobId);if(Number(message.dataGeneration)!==job.dataGeneration){job.reject(CoreUtil.error('COMPUTE-STALE-003','Background result is stale.'));return true}job.resolve(message)}else if(message.status==='error'){clearTimeout(job.timeout);this.jobs.delete(message.jobId);job.reject(CoreUtil.error('COMPUTE-WORKER-004',message.error||'Worker failed.'))}return true}
    cancel(jobId){const job=this.jobs.get(jobId);if(!job)return false;clearTimeout(job.timeout);this.jobs.delete(jobId);this.worker?.postMessage({protocol:this.protocol,protocolVersion:this.protocolVersion,jobId,status:'cancel'});job.reject(CoreUtil.error('COMPUTE-CANCELLED-005','Background computation cancelled.'));return true}
    activeJob(){return this.jobs.keys().next().value||''}
  }'''
p.write_text(s[:start] + new + s[end:])
