'use strict';
const PROTOCOL='LifeOSCompute';
const PROTOCOL_VERSION=1;
const ALLOWED_JOB_TYPES=new Set(['aggregate','monte-carlo']);
const cancelledJobs=new Set();
function validEnvelope(m){return Boolean(m&&m.protocol===PROTOCOL&&m.protocolVersion===PROTOCOL_VERSION&&typeof m.jobId==='string'&&m.jobId.length)}
function post(jobId,status,extra={}){self.postMessage({protocol:PROTOCOL,protocolVersion:PROTOCOL_VERSION,jobId,status,...extra})}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function seed(value){let h=2166136261;for(const ch of String(value||'lifeos')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function random(state){state.value=(Math.imul(1664525,state.value)+1013904223)>>>0;return state.value/4294967296}
function percentile(values,p){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),i=Math.max(0,Math.min(sorted.length-1,Math.floor((sorted.length-1)*p)));return sorted[i]}
async function aggregate(jobId,payload,dataGeneration){const raw=Array.isArray(payload?.values)?payload.values:[];let count=0,sum=0;for(let i=0;i<raw.length;i++){if(cancelledJobs.has(jobId))return;const v=Number(raw[i]);if(Number.isFinite(v)){count++;sum+=v}if(i&&i%4096===0){post(jobId,'progress',{progress:i/raw.length,stage:'Calculating',dataGeneration});await new Promise(r=>setTimeout(r,0))}}if(!cancelledJobs.has(jobId))post(jobId,'complete',{dataGeneration,result:{count,sum,average:count?sum/count:0}})}
async function monteCarlo(jobId,payload,dataGeneration){const simulations=clamp(Math.round(Number(payload?.simulations||2000)),1,5000),remaining=Math.max(0,Number(payload?.remainingMinutes||0)),capacities=(Array.isArray(payload?.capacityByDay)?payload.capacityByDay:[]).map(Number).filter(v=>Number.isFinite(v)&&v>=0),deadlineDays=Math.max(0,Math.round(Number(payload?.deadlineDays??Math.max(0,capacities.length-1)))),effortSigma=clamp(Number(payload?.effortSigma??.2),0,1),capacitySigma=clamp(Number(payload?.capacitySigma??.1),0,1),state={value:seed(payload?.seed||'lifeos-4.2')},completionDays=[];let byDeadline=0,late13=0,lateMore=0;for(let run=0;run<simulations;run++){if(cancelledJobs.has(jobId))return;const need=remaining*clamp(1+(random(state)*2-1)*effortSigma,.4,2.5);let done=0,finish=capacities.length+Math.ceil(need/Math.max(1,capacities.reduce((a,b)=>a+b,0)/Math.max(1,capacities.length)));for(let day=0;day<capacities.length;day++){done+=capacities[day]*clamp(1+(random(state)*2-1)*capacitySigma,0,2);if(done>=need){finish=day;break}}completionDays.push(finish);if(finish<=deadlineDays)byDeadline++;else if(finish<=deadlineDays+3)late13++;else lateMore++;if((run+1)%100===0||run+1===simulations){post(jobId,'progress',{progress:(run+1)/simulations,stage:`Running simulations ${run+1} / ${simulations}`,dataGeneration});await new Promise(r=>setTimeout(r,0))}}if(cancelledJobs.has(jobId))return;post(jobId,'complete',{dataGeneration,result:{simulations,byDeadlineProbability:byDeadline/simulations,lateOneToThreeProbability:late13/simulations,lateMoreThanThreeProbability:lateMore/simulations,medianCompletionDay:percentile(completionDays,.5),p10CompletionDay:percentile(completionDays,.1),p90CompletionDay:percentile(completionDays,.9),bucketsSum:(byDeadline+late13+lateMore)/simulations,seed:String(payload?.seed||'lifeos-4.2')}})}
self.addEventListener('message',event=>{const m=event.data;if(!validEnvelope(m))return;const {jobId}=m;if(m.status==='cancel'){cancelledJobs.add(jobId);return}if(!ALLOWED_JOB_TYPES.has(m.type)){post(jobId,'error',{error:'Unsupported compute job.'});return}cancelledJobs.delete(jobId);const op=m.type==='monte-carlo'?monteCarlo:aggregate;op(jobId,m.payload,Number(m.dataGeneration||0)).catch(error=>post(jobId,'error',{error:error?.message||'Worker failed.'})).finally(()=>cancelledJobs.delete(jobId))});
